apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-hlpr
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-hlpr
  type: LoadBalancer